---
title: "Fitting new data"
output: html_notebook
---


```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(caTools)
  library(ChromComFit)
  library(ChromComParse)
})

source("../shiny/parsing_states/R/setup.R")
```


# Read all data

```{r, echo=FALSE}
info <- ChromComParse::get_info("../data")

info_1 <- info
info_1$metadata <- info$metadata |> 
  filter(condition == "Thy_NCAPD2" & cell_line == "TT204")
info_2 <- info
info_2$metadata <- info$metadata |> 
  filter(condition == "Thy_NCAPD2" & cell_line == "TT234")

raw_1 <- ChromComParse::read_cells(info_1, CELL_SHEETS, EXTVOL_SHEETS, verbose = FALSE)
raw_2 <- ChromComParse::read_cells(info_2, CELL_SHEETS, EXTVOL_SHEETS, verbose = FALSE)
```

```{r}
cells_1 <- ChromComParse::process_raw_data(raw_1)
cells_2 <- ChromComParse::process_raw_data(raw_2)
```

# TT204 NCAPD2

```{r}
params_1 <- list(
  dist.black_lightblue = 0,
  dist.darkblue_brown = 0.75,
  dist.red_pink = 0.4,
  dist.brown_redpink = 0.2,
  black.length = 5,
  angle.red_pink = 45,
  rule.red_pink = RED_PINK_RULES[1]
)

parsed_1 <- ChromComParse::parse_xyz_data(cells_1, params_1) |> pluck("parsed")
echr_1 <- ChromComFit::parsed_to_chrcom3(parsed_1)

plot_timelines(echr_1, smooth = TRUE, k = 9)
```

```{r}
fitpars <- ChromComFit::cpars(
  t0 = 0,
  tau1 = 15,
  tau2 = 8,
  k1 = 0.05,
  k2 = 0.06,
  t2ref = 1
)
free <- c("tau1", "k1", "k2", "tau2")

fit_1 <- ChromComFit::fit_chr(echr_1, fitpars, free, ncells = 100, ntry = 30, ncores = 6)
```

```{r}
plot_timelines(fit_1, smooth = TRUE, k = 5, expdata = echr_1, withpars = TRUE)
```
